version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: book_postgres
    restart: always
    environment:
      POSTGRES_USER: bookmanagementapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookdatabase
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
